#!/usr/bin/env bash
#
# make-srpm.sh           build SRPM only          → ~/rpmbuild/SRPMS/
# make-srpm.sh --rpm     SRPM + binary RPM        → ~/rpmbuild/RPMS/<arch>/
#
# Pinned upstream commits and API credentials are kept in two places:
#   - spec file (tdlib-purple.spec) next to this script  — commit pins
#   - api-credentials.conf next to this script           — API_ID / API_HASH
#
# If api-credentials.conf is missing, the script prompts and creates it.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPEC="$HERE/tdlib-purple.spec"
CREDS="$HERE/api-credentials.conf"
PATCH1="$HERE/01-runtime-api-credentials.patch"
PATCH2="$HERE/02-display-name-fallback.patch"

# Commit pins — must match spec
PURPLE_REPO="https://github.com/BenWiederhake/tdlib-purple.git"
PURPLE_COMMIT="43e6cc2"
PURPLE_VERSION="0.8.1"

TDLIB_REPO="https://github.com/tdlib/td.git"
TDLIB_COMMIT="8d08b34e22a08e58db8341839c4e18ee06c516c5"
TDLIB_VERSION="1.8.35"

CACHE_DIR="${TMPDIR:-/tmp}/tdlib-purple-rpmbuild-cache"
RPM_TOP="$HOME/rpmbuild"

# ----------------------------------------------------------------------------
# Args
# ----------------------------------------------------------------------------
BUILD_RPM=0
for a in "$@"; do
    case "$a" in
        --rpm) BUILD_RPM=1 ;;
        -h|--help)
            sed -n '2,11p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Unknown option: $a" >&2
            exit 2
            ;;
    esac
done

# ----------------------------------------------------------------------------
# Sanity
# ----------------------------------------------------------------------------
for f in "$SPEC" "$PATCH1" "$PATCH2"; do
    [[ -f "$f" ]] || { echo "FAIL: missing $f" >&2; exit 1; }
done

command -v rpmbuild >/dev/null \
    || { echo "FAIL: rpmbuild not installed (dnf install rpm-build rpmdevtools)" >&2; exit 1; }
command -v git >/dev/null \
    || { echo "FAIL: git not installed" >&2; exit 1; }

# ----------------------------------------------------------------------------
# API credentials — prompt if missing
# ----------------------------------------------------------------------------
load_creds() {
    # shellcheck disable=SC1090
    source "$CREDS"
    if [[ -z "${api_id:-}" || -z "${api_hash:-}" ]]; then
        echo "FAIL: $CREDS exists but api_id / api_hash empty" >&2
        exit 1
    fi
}

prompt_creds() {
    cat <<EOF

API credentials file not found:
    $CREDS

Get your pair at https://my.telegram.org/apps (Desktop platform, any URL).
Values will be saved to the file above with chmod 600.

EOF
    local id hash
    while :; do
        read -r -p "API_ID (integer): " id
        if [[ "$id" =~ ^[0-9]+$ && "$id" -gt 0 ]]; then
            break
        fi
        echo "  -> must be a positive integer, try again" >&2
    done
    while :; do
        read -r -p "API_HASH (32 hex chars): " hash
        if [[ "$hash" =~ ^[0-9a-fA-F]{32}$ ]]; then
            break
        fi
        echo "  -> must be exactly 32 hex chars, try again" >&2
    done
    umask 077
    cat > "$CREDS" <<EOF
# Generated by make-srpm.sh -- NOT for version control
# Get a new pair at https://my.telegram.org/apps
api_id=$id
api_hash=$hash
EOF
    chmod 600 "$CREDS"
    echo "Saved $CREDS"
}

if [[ ! -f "$CREDS" ]]; then
    prompt_creds
fi
load_creds

# ----------------------------------------------------------------------------
# Source tarballs (cached, regenerated only if commit changes)
# ----------------------------------------------------------------------------
mkdir -p "$CACHE_DIR"

mk_tarball() {
    # Args: repo_url, commit, version, tarball_name
    local repo="$1" commit="$2" version="$3" name="$4"
    local target="$CACHE_DIR/$name"
    local stamp="$CACHE_DIR/${name}.commit"

    if [[ -f "$target" && -f "$stamp" && "$(cat "$stamp")" == "$commit" ]]; then
        echo "  cache hit: $name"
        return
    fi

    local work
    work="$(mktemp -d -p "$CACHE_DIR" tmp.XXXXXXXX)"
    trap "rm -rf '$work'" RETURN

    echo "  clone+archive: $name"
    git clone --quiet "$repo" "$work/repo"
    (cd "$work/repo" && git checkout --quiet "$commit")

    # Inside the tarball we want a single top-level directory with the right name
    local prefix="${name%.tar.gz}"
    (cd "$work/repo" && git archive --prefix="$prefix/" HEAD) | gzip -9 > "$target"
    echo "$commit" > "$stamp"
}

echo "[1/4] Preparing source tarballs in $CACHE_DIR"
mk_tarball "$PURPLE_REPO" "$PURPLE_COMMIT" "$PURPLE_VERSION" \
           "tdlib-purple-${PURPLE_VERSION}.tar.gz"
mk_tarball "$TDLIB_REPO"  "$TDLIB_COMMIT"  "$TDLIB_VERSION" \
           "tdlib-${TDLIB_VERSION}.tar.gz"

# ----------------------------------------------------------------------------
# rpmbuild tree
# ----------------------------------------------------------------------------
echo "[2/4] Setting up $RPM_TOP"
mkdir -p "$RPM_TOP"/{SOURCES,SPECS,SRPMS,RPMS,BUILD,BUILDROOT}

cp -f "$CACHE_DIR/tdlib-purple-${PURPLE_VERSION}.tar.gz" "$RPM_TOP/SOURCES/"
cp -f "$CACHE_DIR/tdlib-${TDLIB_VERSION}.tar.gz"          "$RPM_TOP/SOURCES/"
cp -f "$PATCH1" "$PATCH2" "$RPM_TOP/SOURCES/"
cp -f "$SPEC" "$RPM_TOP/SPECS/"

# ----------------------------------------------------------------------------
# Build SRPM (creds NOT embedded)
# ----------------------------------------------------------------------------
echo "[3/4] Building SRPM"
# Force C locale so rpmbuild output is parseable (avoids translated "Wrote:")
SRPM_PATH="$(
    LC_ALL=C rpmbuild -bs "$RPM_TOP/SPECS/tdlib-purple.spec" 2>&1 | tee /tmp/srpm.log \
        | awk '/^Wrote: / { print $2 }'
)"
[[ -f "$SRPM_PATH" ]] || { echo "FAIL: SRPM not produced (see /tmp/srpm.log)" >&2; exit 1; }
echo "  → $SRPM_PATH"

# ----------------------------------------------------------------------------
# Optional binary RPM
# ----------------------------------------------------------------------------
if [[ $BUILD_RPM -eq 1 ]]; then
    echo "[4/4] Rebuilding binary RPM from SRPM (creds injected via --define)"
    LC_ALL=C rpmbuild --rebuild \
        --define "_api_id $api_id" \
        --define "_api_hash $api_hash" \
        "$SRPM_PATH"
    echo ""
    echo "Binary RPM:"
    find "$RPM_TOP/RPMS" -name 'tdlib-purple-*.rpm' -newer "$SRPM_PATH" -printf "  %p\n"
else
    echo "[4/4] Skipping binary RPM build (use --rpm to enable)"
fi

echo ""
echo "Done."
