# Build with:
#   make-srpm.sh           # SRPM only
#   make-srpm.sh --rpm     # SRPM + binary RPM
#
# API_ID/API_HASH are NOT in the spec or in the SRPM. They are supplied at
# rpmbuild time via --define "_api_id NNN" --define "_api_hash HEX", by the
# make-srpm.sh wrapper. If the rebuild is invoked manually without those
# defines, the upstream compile-time fallback (94575/...) is used, but the
# Telegram server currently rejects that pair with UPDATE_APP_TO_LOGIN.

%global tdlib_version  1.8.35
%global tdlib_commit   8d08b34e22a08e58db8341839c4e18ee06c516c5
%global purple_commit  43e6cc2

# Fall back to upstream default credentials if --define not supplied.
%{!?_api_id:   %global _api_id   94575}
%{!?_api_hash: %global _api_hash a3406de8d171bb422bb6ddf3bbd800e2}

Name:           tdlib-purple
Version:        0.8.1
Release:        1.ben%{?dist}
Summary:        Telegram protocol plugin for libpurple (Pidgin) using TDLib

License:        GPL-2.0-or-later
URL:            https://github.com/radek-bucek/tdlib-purple
# Generated by make-srpm.sh from upstream commits %%{purple_commit} / %%{tdlib_commit}
Source0:        tdlib-purple-%{version}.tar.gz
Source1:        tdlib-%{tdlib_version}.tar.gz
Patch0:         01-runtime-api-credentials.patch
Patch1:         02-display-name-fallback.patch

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  make
BuildRequires:  gperf
BuildRequires:  openssl-devel
BuildRequires:  zlib-devel
BuildRequires:  libpurple-devel
BuildRequires:  gettext

Requires:       libpurple

%description
Telegram protocol plugin for libpurple, allowing Pidgin (and other
libpurple-based clients) to connect to Telegram. Built from the
BenWiederhake fork of tdlib-purple with statically-linked TDLib
%{tdlib_version} — no runtime dependency on a system TDLib package.

Built-in API credentials can be overridden at runtime (priority high to low):
  1. Per-account "API id"/"API hash" field in Pidgin account editor
  2. Environment: TELEGRAM_API_ID / TELEGRAM_API_HASH
  3. File: ~/.purple/telegram-tdlib-api.conf
  4. Compile-time defaults baked into this RPM

%prep
%setup -q -n tdlib-purple-%{version}
# Unpack TDLib source into td/ subdirectory (replaces git submodule layout)
mkdir -p td
tar xf %{SOURCE1} --strip-components=1 -C td
%patch -P0 -p1
%patch -P1 -p1

%build
# Phase 1: Build TDLib (static), install to a staging tree inside %{_builddir}
mkdir -p td-build
pushd td-build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=%{_builddir}/td-install \
    ../td
make %{?_smp_mflags}
make install
popd

# Phase 2: Build tdlib-purple plugin against staged TDLib, with API creds baked in
mkdir -p plugin-build
pushd plugin-build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DTd_DIR=%{_builddir}/td-install/lib/cmake/Td \
    -DNoVoip=True \
    -DAPI_ID=%{_api_id} \
    -DAPI_HASH=%{_api_hash} \
    ..
make %{?_smp_mflags}
popd

%install
pushd plugin-build
make install DESTDIR=%{buildroot}
popd

%files
%license LICENSE
%doc README.md
%{_libdir}/purple-2/libtelegram-tdlib.so
%{_datadir}/pixmaps/pidgin/protocols/16/telegram.png
%{_datadir}/pixmaps/pidgin/protocols/22/telegram.png
%{_datadir}/pixmaps/pidgin/protocols/48/telegram.png
%{_datadir}/metainfo/tdlib-purple.metainfo.xml
%{_datadir}/locale/*/LC_MESSAGES/tdlib-purple.mo

%changelog
* Sun May 24 2026 jumbox <bezbolestnypekac@gmail.com> - 0.8.1-1.ben
- Initial RPM packaging of BenWiederhake fork of tdlib-purple
- Statically linked against TDLib %{tdlib_version} (commit %{tdlib_commit})
- Patch: runtime API_ID/API_HASH override (env, ~/.purple/.conf, per-account UI)
- Patch: display name fallback to @username / +phone / idXXX
